dairy/urls.py
from django.conf.urls import patterns, include, url

from django.contrib import admin
admin.autodiscover()

urlpatterns = patterns('',

    url(r'^i18n/', include('django.conf.urls.i18n')),
    url(r'^$', 'cow.views.index', name='home'),
    url(r'^all_tasks/$', 'cow.views.all_tasks', name='all_tasks'),
    url(r'^add_cow/', 'cow.views.add_cow', name='add_cow'),
    url(r'^cows/', 'cow.views.cows_list', name='cows'),
    url(r'^tasks/', 'cow.views.tasks_list', name='tasks'),
    url(r'^add_health_task/', 'cow.views.add_health_task', name='add_health_task'),
    url(r'^settings/', 'cow.views.settings', name='settings'),
    url(r'^dairy/', 'cow.views.dairy_profile', name='dairy'),
    url(r'^home/', 'cow.views.homepage', name='homepage'),
    url(r'^post_status/', 'cow.views.post_status', name='post_status'),
    url(r'^task/(?P<task_id>\d+)/$', 'cow.views.health_task', name='health_task'),
    url(r'^cow/(?P<cow_id>\d+)/$', 'cow.views.cow_profile', name='cow_profile'),
    url(r'^update_cow/(?P<cow_id>\d+)/$', 'cow.views.update_cow', name='update_cow'),
    url(r'^cow/delete/confirm/(?P<cow_id>\d+)/$', 'cow.views.delete_confirm', name='delete_confirm'),
    url(r'^cow/delete/(?P<cow_id>\d+)/$', 'cow.views.delete_cow', name='delete_cow'),
    url(r'^task/delete/confirm/(?P<task_id>\d+)/$', 'cow.views.task_delete_confirm', name='task_delete_confirm'),
    url(r'^task/delete/(?P<task_id>\d+)/$', 'cow.views.delete_task', name='delete_task'),

    #pregnancy module 

    
    url(r'^pregnancy/$', 'pregnancy.views.index', name='pregnancy_index'),
    url(r'^pregnancy/add_record/$', 'pregnancy.views.add_record', name='pregnancy_add_record'),

    url(r'^pregnancy/record/(?P<pregnancy_id>\d+)/$', 'pregnancy.views.view_record', name='view_record'),
    url(r'^pregnancy/add_heat/(?P<pregnancy_id>\d+)/$', 'pregnancy.views.add_heat', name='add_heat'),
    url(r'^pregnancy/add_parturition/(?P<pregnancy_id>\d+)/$', 'pregnancy.views.add_parturition', name='add_pasturition'),
    url(r'^pregnancy/add_conceieved/(?P<pregnancy_id>\d+)/$', 'pregnancy.views.add_conceieved', name='add_conceieved'),
    url(r'^pregnancy/add_pregnant/(?P<pregnancy_id>\d+)/$', 'pregnancy.views.add_pregnant', name='add_pregnant'),
    url(r'^pregnancy/add_treatment/(?P<pregnancy_id>\d+)/$', 'pregnancy.views.add_treatment', name='add_treatment'),
    url(r'^pregnancy/result/(?P<stage>\w+)/(?P<stage_id>\d+)/$', 'pregnancy.views.add_result', name='add_treatment'),


    url(r'^alerts/$', 'alerts.views.index', name='alerts'),
    url(r'^alerts/add_number/$', 'alerts.views.add_mobile_number', name='add_number'),
    url(r'^status/$', 'alerts.views.cow_status', name='cow_status'),
    
    
    url(r'^milk/$', 'cow.views.milk', name='cow_milk'),
    url(r'^milk/report/$', 'cow.views.milk_report', name='cow_milk_report'),
    url(r'^add_milk/$', 'cow.views.add_milk_view', name='add_cow_milk'),
    url(r'^milk/add/$', 'cow.views.add_milk', name='add_cow_milk'),
    url(r'^zohoverify/verifyforzoho.html/$', 'cow.views.zoho', name='zoho'),
    url(r'^signup/$', 'cow.views.signup', name='signup'),




    url(r'^comments/', include('django_comments.urls')),


    url(r'^update_task/(?P<task_id>\d+)/$', 'cow.views.update_health_task', name='update_health_task'),
    url(r'^add_next_task/(?P<task_id>\d+)/$', 'cow.views.add_next_health_task', name='next_health_task'),
    # url(r'^blog/', include('blog.urls')),
    (r'^accounts/login/$', 'django.contrib.auth.views.login', {'template_name': 'login.html'}),
    (r'^accounts/logout/$', 'django.contrib.auth.views.logout', {'next_page':'/accounts/login/','template_name': 'login.html'}),
    url(r'^admin/', include(admin.site.urls)),
    url(r'^tracking/', include('tracking.urls')),
)



from django.conf import settings
from django.conf.urls.static import static

urlpatterns =urlpatterns + patterns('',
    # ... the rest of your URLconf goes here ...
) + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)


from django.conf import settings

if 'rosetta' in settings.INSTALLED_APPS:
    urlpatterns += patterns('',
        url(r'^rosetta/', include('rosetta.urls')),
    )

cow/models.py
from django.db import models
from django.contrib.contenttypes import generic
from django.contrib.auth.models import User
from django.contrib.contenttypes.models import ContentType
from django.contrib.contenttypes import generic
from django.utils.translation import ugettext_lazy as _

class Dairy(models.Model):
	name = models.CharField(_('name'),max_length=100)
	address = models.TextField(_('address'))
	user = models.ForeignKey(User)
	class Meta:
                app_label = 'cow'
		verbose_name = _('dairy')
        def __unicode__(self):
                return '%s' % (self.name)


class UserProfile(models.Model):
	mobile_number = models.CharField(_('name'),max_length=100)
	address = models.CharField(max_length=255)
	
class CowProfile(models.Model):
	name = models.CharField(_('name'),max_length=100)
	date_of_birth = models.DateField(_('date of birth'))
	description = models.TextField(_('description'))
	photo = models.ImageField(_('photo'),upload_to='cows',null=True,blank=True)
	breed = models.CharField(_('breed'),max_length=100)
        tasks = generic.GenericRelation('HealthTask')
	dairy = models.ForeignKey(Dairy)

	class Meta:
	        app_label = 'cow'
		verbose_name = _('cattle')
        def __unicode__(self):
                return '%s' % (self.name)

class HealthTask(models.Model):
	cow = models.ForeignKey(CowProfile)
	task_name = models.CharField(_('task name'),max_length=100)
	task_details = models.TextField(_('task details'))
	added_on = models.DateField(_('added on'))
	due_date = models.DateField(_('due date'))
	completed_on = models.DateField(_('completed on'),null=True)
	result = models.TextField(_('result'),null=True)
	parent_task = models.ForeignKey('self',null= True)
	task_completed = models.BooleanField(_('task completed'))

	content_type = models.ForeignKey(ContentType)
    	object_id = models.PositiveIntegerField()
    	content_object = generic.GenericForeignKey('content_type', 'object_id')

	class Meta:
                app_label = 'cow'
		verbose_name = _('health task')

        def __unicode__(self):
                return '%s' % (self.task_name)

class Notifications(models.Model):
	email_notifications = models.BooleanField(_('email notifications'))
	sms_notifications = models.BooleanField(_('sms notifications'))
	mobile_number = models.IntegerField(_('mobile number'))
	user = models.OneToOneField(User)

class Status(models.Model):
	cow = models.ForeignKey(CowProfile,null=True,blank=True)
	task_name = models.TextField(_('task name'))
	image = models.ImageField(_('image'),upload_to='media',null=True,blank=True)
	due_date = models.DateField(_('due date'))
	user = models.ForeignKey(User)	
	dairy = models.ForeignKey(Dairy)
	class Meta:
                app_label = 'cow'
		verbose_name = _('status')

        def __unicode__(self):
                return '%s' % (self.task_name)


class UserDairy(models.Model):
	user = models.ForeignKey(User)
	dairy = models.ForeignKey(Dairy)
	class Meta:
		verbose_name = _('dairy')

class Milk(models.Model):
	dairy = models.ForeignKey(Dairy)
	morning = models.FloatField(_('morning'))
	evening = models.FloatField(_('evening'))
	date = models.DateField(_('date'))
	cow = models.ForeignKey(CowProfile)
	
	class Meta:
		verbose_name = _('milk')
import urllib
import httplib

def send_sms(mobilenumber,text):
	conn = httplib.HTTPConnection("smslane.com")
	mobile_number = '91'+str(mobilenumber)
	params = urllib.urlencode({'user': 'skbohra123', 'password': '461354','msisdn':mobile_number,'sid':'WebSMS','msg':text,'fl':'0'})
	url = "http://smslane.com/vendorsms/pushsms.aspx?%s" % params
	conn.request("GET", url)
	r1 = conn.getresponse()
	print "data -"
	print r1.read()
	conn.close()
	



from celery.decorators import task
from cow.models import HealthTask
from django.core.mail import send_mail

from django.core.mail import EmailMultiAlternatives

@task
def send_reminder(pk):
    task = HealthTask.objects.get(id=pk)
    if task.cow.dairy.user.notifications.email_notifications == True:
    	html_body = "Hi <br><br> Your cow %s needs to be checked for the task - %s today! This is a reminder for the same! <br><br> Cheers<br> DairyHealth" % (task.cow, task.task_name)	
    	body = "Hi, Your cow %s needs to be checked for the task - %s today! This is a reminder for the same! Cheers" % (task.cow, task.task_name)	
    	to = [task.cow.dairy.user.email,"shreekant@ringad.net",]
    	subject = "DairyHealth - Health Task for today reminder"
    	msg = EmailMultiAlternatives(subject, body, "info@dairyhealth.cu.cc", to)
    	msg.attach_alternative(html_body, "text/html") 
    	msg.send()
    if task.cow.dairy.user.notifications.sms_notifications == True:
	mobile = task.cow.dairy.user.notifications.mobile_number
    	body = "Hi, Your cow %s needs to be checked for the task - %s today! This is a reminder for the same! Cheers" % (task.cow, task.task_name)        
        send_sms(mobile,body)	


from django.db.models.signals import post_save

from datetime import time
from datetime import datetime
from datetime import timedelta
import pytz

def reminder_handler(sender,instance, **kwargs):
	#tomorrow = datetime.datetime.now()+datetime.timedelta(seconds=30)
	indian = pytz.timezone("Asia/Kolkata")
	tomorrow = datetime.combine(instance.due_date, time(12,05,10))
	date = indian.localize(tomorrow)
	send_reminder.apply_async(eta=date, kwargs={'pk': instance.id})

#post_save.connect(reminder_handler, sender=HealthTask) 	

cow/forms.py
from django.forms import ModelForm
from django import forms
from cow.models import Dairy,CowProfile,HealthTask,Notifications,Status
from django.contrib.auth.models import User

class DairyForm(ModelForm):
	class Meta:
		model = Dairy
		exclude = ('user',)

class NotificationsForm(ModelForm):
	class Meta:
		model = Notifications
		exclude = ('user',)
class CowProfileForm(ModelForm):
	class Meta:
		model = CowProfile
		exclude = ('dairy',)
class HealthTaskForm(ModelForm):
	class Meta:
		model = HealthTask
		exclude = ('content_type','object_id','completed_on','result','parent_task','added_on','task_completed',)


class HealthTaskCompletedForm(ModelForm):
	class Meta:
		model = HealthTask
		fields = ('result',)

class StatusForm(ModelForm):
	class Meta:
		model = Status
		exclude = ('due_date','user','dairy',)
	def __init__(self, dairy, *args, **kwargs):
        	super(StatusForm, self).__init__(*args, **kwargs)
        	self.fields['cow'].queryset=CowProfile.objects.filter(dairy=dairy)


class MilkSearchForm(forms.Form):
	date = forms.DateField()



class UserForm(forms.Form):
	username = forms.CharField(max_length=30)
	first_name = forms.CharField()
	last_name = forms.CharField()
	password1=forms.CharField(max_length=30,widget=forms.PasswordInput(),label="Password") #render_value=False
	password2=forms.CharField(max_length=30,widget=forms.PasswordInput(),label="Repeat Password")
	email=forms.EmailField(required=False)
        mobile_number = forms.IntegerField()	
	address = forms.CharField()
	def clean_username(self): # check if username dos not exist before
    		try:
        		User.objects.get(username=self.cleaned_data['username']) #get user from user model
    		except User.DoesNotExist :
        		return self.cleaned_data['username']

    		raise forms.ValidationError("this user exist already")


	def clean(self): # check if password 1 and password2 match each other
    		if 'password1' in self.cleaned_data and 'password2' in self.cleaned_data:#check if both pass first validation
        		if self.cleaned_data['password1'] != self.cleaned_data['password2']: # check if they match each other
            			raise forms.ValidationError("passwords dont match each other")
    		return self.cleaned_data


	def clean_mobile_number(self): # check if scholar_id dos not exist before
    		data = self.cleaned_data['mobile_number']
        	length = len(str(data))
		if length ==10:
			return self.cleaned_data['mobile_number']

    		raise forms.ValidationError("Mobile number should be of 10 digits")

templates/cow/add_cow.html
{%extends 'cow/index.html'%}
{% load bootstrap3 %}

{% load i18n %} 
{%block title%} {%trans "Add Cow Details"%}{%endblock%}
{%block content%}
	<div class="row-fluid ">	
				<div class="box span12">
					<div class="box-header">
						<h2><i class="halflings-icon hand-top"></i><span class="break"></span>{%trans "Animal Record"%}</h2>
					</div>
					<div class="box-content">
	



{% bootstrap_messages %}


<form action="" method="post" enctype= "multipart/form-data" class="form">
    {% csrf_token %}
    {% bootstrap_form form %}
    {% buttons %}
        <button type="submit" class="btn btn-primary">
            {% bootstrap_icon "star" %} {%trans "Next"%}
        </button>
    {% endbuttons %}
</form>


</div>
{%endblock%}


{%block bottom%}
{%endblock%}

templates/cow/add_health_task.html
{%extends 'cow/index.html'%}
{% load bootstrap3 %}
{% load i18n %}
{%block title%} {%trans "Add Health Task"%} {%endblock%}
{%block content%}
  <div class="row-fluid ">	
				<div class="box span12">
					<div class="box-header">
						<h2><i class="halflings-icon hand-top"></i><span class="break"></span>{%trans "Create health task"%}</h2>
					</div>
					<div class="box-content">
	



{% bootstrap_messages %}

<div class="alert alert-info">
							<button data-dismiss="alert" class="close" type="button">×</button>
							<strong>{%trans "Heads up!"%}</strong> 
{%trans "You will get an alert for this task on the due date"%}
						</div>


<form action="" method="post" enctype= "multipart/form-data" class="form">
    {% csrf_token %}
    {% bootstrap_form form %}
    {% buttons %}
        <button type="submit" class="btn btn-primary">
            {% bootstrap_icon "star" %} {%trans "Submit"%}
        </button>
    {% endbuttons %}
</form>

</div>
{%endblock%}


{%block bottom%}
{%endblock%}

templates/cow/confirm_delete.html
{%extends 'cow/index.html'%}
{% load bootstrap3 %}
{%load i18n%}
{%block title%}{%trans "Delete cattle record"%} - {{cow.name}} {%endblock%}
{%block content%}
  <div class="row-fluid ">	
				<div class="box span12">
					<div class="box-header">
						<h2><i class="halflings-icon hand-top"></i><span class="break"></span>{%trans "Delete Animal Record?"%}</h2>
					</div>
					<div class="box-content">
	



{% bootstrap_messages %}

<div class="panel panel-default">
        <!-- Default panel contents -->


<table class="table">
<tr>
<td>
{%trans "Cattle Name"%}:
</td>
<td>
{{cow.name}}
</td>
<tr>
<td>
{%trans "Do you really	 want to delete this cattle record"%}?
</td>
<td>
<a class="btn btn-danger" href="/cow/delete/{{cow.id}}/">{%trans "Yes, delete"%}</a>
</td>
</tr>



</table>


     </div>
</div>
{%endblock%}


{%block bottom%}
{%endblock%}

templates/cow/index.html
{%load staticfiles%}
{% load i18n %} 
{% load bootstrap3 %}


<!DOCTYPE html>
<html lang="en">
<head>
	
	<!-- start: Meta -->
	<meta charset="utf-8" />
	<title>{%block title%}{%trans "Cattlebook"%}{%endblock%}</title>
	<meta name="description" content="Cattlebook, cattle health management" />

	<meta name="keyword" content="cattle health" />
	<!-- end: Meta -->
	
	<!-- start: Mobile Specific -->
	<meta name="viewport" content="width=device-width, initial-scale=1" />
	<!-- end: Mobile Specific -->
	
	<!-- start: CSS -->
	<link href="{%static "acme/css/bootstrap.min.css"%}" rel="stylesheet" />
	<link href="{%static "acme/css/bootstrap-responsive.min.css"%}" rel="stylesheet" />
	<link href="{%static "acme/css/style.min.css"%}" rel="stylesheet" />
	<link href="{%static "acme/css/style-responsive.min.css"%}" rel="stylesheet" />
	<link href="{%static "acme/css/retina.css"%}" rel="stylesheet" />
	<link href="{%static "acme/css/mine.css"%}" rel="stylesheet" />
<link href="{%static "chosen/chosen.min.css"%}" rel="stylesheet">
	<!-- end: CSS -->

	<!-- The HTML5 shim, for IE6-8 support of HTML5 elements -->
	<!--[if lt IE 9]>
	  	<script src="http://html5shim.googlecode.com/svn/trunk/html5.js"></script>
		<link id="ie-style" href="css/ie.css" rel="stylesheet">
	<![endif]-->
	
	<!--[if IE 9]>
		<link id="ie9style" href="css/ie9.css" rel="stylesheet">
	<![endif]-->
	
	<!-- start: Favicon and Touch Icons -->
	<link rel="apple-touch-icon-precomposed" sizes="144x144" href="{%static "acme/ico/apple-touch-icon-144-precomposed.png"%}" />
	<link rel="apple-touch-icon-precomposed" sizes="114x114" href="{%static "acme/ico/apple-touch-icon-114-precomposed.png"%}" />
	<link rel="apple-touch-icon-precomposed" sizes="72x72" href="{%static "acme/ico/apple-touch-icon-72-precomposed.png"%}" />
	<link rel="apple-touch-icon-precomposed" href="{%static "acme/ico/apple-touch-icon-57-precomposed.png"%}" />
	<!-- end: Favicon and Touch Icons -->
	
		
		
		
<meta http-equiv="Content-Type" content="text/html; charset=utf-8" /></head>

<body>
		<!-- start: Header -->
	<div class="navbar">
		<div class="navbar-inner">
			<div class="container-fluid">
								
				<!-- start: Header Menu -->
				<div class="nav-no-collapse header-nav">
					<ul class="nav">
						<li>
<a href="/">
								<i class="halflings-icon white home"></i>
</a>
</li>
						<li>
							<a class="btn" href="/alerts/">
								<i class="halflings-icon white warning-sign"></i>
							</a>
						</li>
						
<!-- start: User Dropdown -->
						<li class="dropdown">
							<a class="btn dropdown-toggle" data-toggle="dropdown" href="#">
								<i class="halflings-icon white list"></i> 
								<span class="caret"></span>
							</a>
							<ul class="dropdown-menu">
								<li><a href="/cows/"><i class="fa fa-database"></i>{%trans "Animals"%}</a></li>
								<li><a href="/pregnancy/"><i class="fa fa-venus-mars"></i>{%trans "Reproduction"%}</a></li>
								<li><a href="/milk/"><i class="fa fa-coffee"></i>{%trans "Milk"%}</a></li>
								<li><a href="/alerts/"><i class="fa fa-bullhorn"></i>{%trans "Alerts"%}</a></li>
								<li><a href="/tasks/"><i class="fa fa-tasks"></i>{%trans "Tasks"%}</a></li>
								<li><a href="/status/"><i class="fa fa-tachometer"></i>{%trans "Status"%}</a></li>
							</ul>
						</li>



<!-- start: User Dropdown -->
						<li class="dropdown">
							<a class="btn dropdown-toggle" data-toggle="dropdown" href="#">
								<i class="halflings-icon white user"></i> 
								<span class="caret"></span>
							</a>
							<ul class="dropdown-menu">
								<li><a href="/dairy/"><i class="halflings-icon white user"></i>{%trans "Profile"%}</a></li>
								<li><a href="/settings/"><i class="halflings-icon white wrench"></i>{%trans "Settings"%}</a></li>
								<li><a href="/accounts/logout/"><i class="halflings-icon white off"></i>{%trans "Logout"%}</a></li>
							</ul>
						</li>
						<!-- end: User Dropdown -->
					</ul>
				</div>
				<!-- end: Header Menu -->
				
			</div>
		</div>
	</div>
	<!-- start: Header -->
	
		<div class="container-fluid">
		<div class="row-fluid">
			<div id="content" class="span11">
			{%block content%}
		<div class="row-fluid ">	
				<div class="box span12">
					<div class="box-header">
						<h2><i class="halflings-icon hand-top"></i><span class="break"></span>{%trans "Dashboard"%}</h2>
					</div>
					<div class="box-content">
						
{% bootstrap_messages %}

{%if cow_message%}

<div class="alert alert-danger">
{{cow_message}} <a class="btn" href="/add_cow/">Add Animal</a>
</div>
{%endif%}
						<a class="quick-button span2" href="/cows/">
							<i class=" fa fa-database"></i>
							<p>{%trans "Animals"%}</p>
						</a>
						<a class="quick-button span2" href="/pregnancy/">
							<i class="fa fa-venus-mars"></i>
							<p>{%trans "Reproduction"%}</p>
						</a>
						<a class="quick-button span2" href="/milk/">
							<i class="fa fa-coffee"></i>
							<p>{%trans "Milk"%}</p>
						</a>
						<a class="quick-button span2" href="/alerts/">
							<i class="fa fa-bullhorn"></i>
							<p>{%trans "Alerts"%}</p>
						</a>
						<a class="quick-button span2" href="/tasks/">
							<i class="fa fa-tasks"></i>
							<p>{%trans "Tasks"%}</p>
						</a>
						<a class="quick-button span2" href="/status/">
							<i class="fa fa-tachometer"></i>
							<p>{%trans "Status"%}</p>
						</a>
						<div class="clearfix"></div>
					</div>	
				</div><!--/span-->
				
			</div>	
				
			
       {%endblock%}
					
			<!-- end: Content -->
			
		
		<div class="clearfix"></div>
		
		<footer>
			<p>
				<span style="text-align:left;float:left">&copy; 2015 <a href="http://cattlebook.co" alt="Cattlebook">{%trans "Cattlebook"%}</a></span>

			</p>
		</footer>
				
	</div><!--/.fluid-container-->

	<!-- start: JavaScript-->

		<script src="{%static "acme/js/jquery-1.9.1.min.js"%}"></script>
	<script src="{%static "acme/js/jquery-migrate-1.0.0.min.js"%}"></script>
	
		<script src="{%static "acme/js/jquery-ui-1.10.0.custom.min.js"%}"></script>
	
		<script src="{%static "acme/js/jquery.ui.touch-punch.js"%}"></script>
	
		<script src="{%static "acme/js/modernizr.js"%}"></script>
	
		<script src="{%static "acme/js/bootstrap.min.js"%}"></script>
	
		<script src="{%static "acme/js/jquery.cookie.js"%}"></script>
	
		<script src="{%static "acme/js/fullcalendar.min.js"%}"></script>
	
		<script src="{%static "acme/js/jquery.dataTables.min.js"%}"></script>

		<script src="{%static "acme/js/excanvas.js"%}"></script>
	<script src="{%static "acme/js/jquery.flot.js"%}"></script>
	<script src="{%static "acme/js/jquery.flot.pie.js"%}"></script>
	<script src="{%static "acme/js/jquery.flot.stack.js"%}"></script>
	<script src="{%static "acme/js/jquery.flot.resize.min.js"%}"></script>
		
		<script src="{%static "acme/js/gauge.min.js"%}"></script>

		<script src="{%static "acme/js/jquery.chosen.min.js"%}"></script>
	
		<script src="{%static "acme/js/jquery.uniform.min.js"%}"></script>
		
		<script src="{%static "acme/js/jquery.cleditor.min.js"%}"></script>
	
		<script src="{%static "acme/js/jquery.noty.js"%}"></script>
	
		<script src="{%static "acme/js/jquery.elfinder.min.js"%}"></script>
	
		<script src="{%static "acme/js/jquery.raty.min.js"%}"></script>
	
		<script src="{%static "acme/js/jquery.iphone.toggle.js"%}"></script>
	
		<script src="{%static "acme/js/jquery.uploadify-3.1.min.js"%}"></script>
	
		<script src="{%static "acme/js/jquery.gritter.min.js"%}"></script>
	
		<script src="{%static "acme/js/jquery.imagesloaded.js"%}"></script>
	
		<script src="{%static "acme/js/jquery.masonry.min.js"%}"></script>
	
		<script src="{%static "acme/js/jquery.knob.modified.js"%}"></script>
	
		<script src="{%static "acme/js/jquery.sparkline.min.js"%}"></script>
			<script src="{%static "acme/js/counter.js"%}"></script>
	
		<script src="{%static "acme/js/raphael.2.1.0.min.js"%}"></script>
	<script src="{%static "acme/js/justgage.1.0.1.min.js"%}"></script>
	
		<script src="{%static "acme/js/retina.js"%}"></script>

		<script src="{%static "acme/js/core.min.js"%}"></script>
	
		<script src="{%static "acme/js/charts.js"%}"></script>
	
    <script src="{%static "js/jquery.form.min.js"%}"></script>
		<script src="{%static "acme/js/custom.js"%}"></script>
    <script src="{%static "chosen/chosen.jquery.min.js"%}"></script>
	<!-- end: JavaScript-->
	
  <script>

$(document).ready(function() {
  
 $( "#id_date,#id_due_date,#id_date_of_birth" ).datepicker();
$("#id_cow").chosen();


});


  </script>
<script>
var options = { 

        beforeSubmit:  showRequest,  // pre-submit callback 
        success:       showResponse  // post-submit callback 
 
        // other available options: 
        //url:       url         // override for form's 'action' attribute 
        //type:      type        // 'get' or 'post', override for form's 'method' attribute 
        //dataType:  null        // 'xml', 'script', or 'json' (expected server response type) 
        //clearForm: true        // clear all form fields after successful submit 
        //resetForm: true        // reset the form after successful submit 
 
        // $.ajax options can be used here too, for example: 
        //timeout:   3000 
    }; 
 $(function(){
    // bind form using 'ajaxForm' 
    $('.commentForm').ajaxForm(options); 
    $('.milkForm').ajaxForm(); 

}); 
 
// pre-submit callback 
function showRequest(formData, jqForm, options) { 
    // formData is an array; here we use $.param to convert it to a string to display it 
    // but the form plugin does this for you automatically when it submits the data 
    var queryString = $.param(formData); 
 
    // jqForm is a jQuery object encapsulating the form element.  To access the 
    // DOM element for the form do this: 
    // var formElement = jqForm[0]; 
 
    
    // here we could return false to prevent the form from being submitted; 
    // returning anything other than false will allow the form submit to continue 
    return true; 
} 
 
// post-submit callback 
function showResponse(responseText, statusText, xhr, $form)  { 
    // for normal html responses, the first argument to the success callback 
    // is the XMLHttpRequest object's responseText property 
 
    // if the ajaxForm method was passed an Options Object with the dataType 
    // property set to 'xml' then the first argument to the success callback 
    // is the XMLHttpRequest object's responseXML property 
 
    // if the ajaxForm method was passed an Options Object with the dataType 
    // property set to 'json' then the first argument to the success callback 
    // is the json data object returned by the server     


    window.location = '/';
}  
</script>
{%block bottom_js%}

{%endblock%}

</body>
</html>